//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresy
    {
        public Adresy()
        {
            this.Klienci = new HashSet<Klienci>();
            this.Pracownicy = new HashSet<Pracownicy>();
        }
    
        public int ID { get; set; }
        public string miasto { get; set; }
        public string kod_pocztowy { get; set; }
        public string ulica { get; set; }
        public string nr_domu { get; set; }
    
        public virtual ICollection<Klienci> Klienci { get; set; }
        public virtual ICollection<Pracownicy> Pracownicy { get; set; }
    }
}
