//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROJEKTNGEntities : DbContext
    {
        public PROJEKTNGEntities()
            : base("name=PROJEKTNGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresy> Adresy { get; set; }
        public DbSet<Galeria_zdjęć> Galeria_zdjęć { get; set; }
        public DbSet<Kategorie> Kategorie { get; set; }
        public DbSet<Klienci> Klienci { get; set; }
        public DbSet<Kontakty> Kontakty { get; set; }
        public DbSet<Opinia> Opinia { get; set; }
        public DbSet<Podkategorie> Podkategorie { get; set; }
        public DbSet<Pracownicy> Pracownicy { get; set; }
        public DbSet<Producenci> Producenci { get; set; }
        public DbSet<Produkt> Produkt { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Zamowienia> Zamowienia { get; set; }
        public DbSet<Zamówienia_produkty> Zamówienia_produkty { get; set; }
    }
}
