//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorie
    {
        public Kategorie()
        {
            this.Podkategorie = new HashSet<Podkategorie>();
            this.Produkt = new HashSet<Produkt>();
        }
    
        public int ID { get; set; }
        public string nazwa_kategori { get; set; }
    
        public virtual ICollection<Podkategorie> Podkategorie { get; set; }
        public virtual ICollection<Produkt> Produkt { get; set; }
    }
}
