//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public Klienci()
        {
            this.Opinia = new HashSet<Opinia>();
            this.Zamowienia = new HashSet<Zamowienia>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_adres { get; set; }
        public Nullable<int> ID_kontakt { get; set; }
        public string nazwa_użytkownika { get; set; }
        public string hasło { get; set; }
        public string nazwisko { get; set; }
        public string imię { get; set; }
    
        public virtual Adresy Adresy { get; set; }
        public virtual Kontakty Kontakty { get; set; }
        public virtual ICollection<Opinia> Opinia { get; set; }
        public virtual ICollection<Zamowienia> Zamowienia { get; set; }
    }
}
