//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakty
    {
        public Kontakty()
        {
            this.Klienci = new HashSet<Klienci>();
            this.Pracownicy = new HashSet<Pracownicy>();
        }
    
        public int ID { get; set; }
        public string nr_tel_1 { get; set; }
        public string nr_tel_2 { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Klienci> Klienci { get; set; }
        public virtual ICollection<Pracownicy> Pracownicy { get; set; }
    }
}
