//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinia
    {
        public int ID { get; set; }
        public Nullable<int> ID_Klienci { get; set; }
        public string treść { get; set; }
        public System.DateTime data_wystawienia { get; set; }
    
        public virtual Klienci Klienci { get; set; }
    }
}
