//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public Produkt()
        {
            this.Zamówienia_produkty = new HashSet<Zamówienia_produkty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Producenci { get; set; }
        public Nullable<int> ID_Kategoria { get; set; }
        public Nullable<int> ID_Podkategoria { get; set; }
        public Nullable<int> ID_Galeria_zdjęć { get; set; }
        public string nazwa_produktu { get; set; }
        public string opis { get; set; }
        public Nullable<decimal> cena { get; set; }
    
        public virtual Galeria_zdjęć Galeria_zdjęć { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        public virtual Podkategorie Podkategorie { get; set; }
        public virtual Producenci Producenci { get; set; }
        public virtual ICollection<Zamówienia_produkty> Zamówienia_produkty { get; set; }
    }
}
