//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        public Zamowienia()
        {
            this.Zamówienia_produkty = new HashSet<Zamówienia_produkty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Klienci { get; set; }
        public System.DateTime data_zlożenia_zamówienia { get; set; }
        public bool czy_przyjęto_zamówienie { get; set; }
        public Nullable<System.DateTime> data_przyjęcia_zamówienia { get; set; }
        public string zapłacono { get; set; }
        public Nullable<System.DateTime> data_wysyłki { get; set; }
        public bool czy_zamówienie_zrealizowano { get; set; }
        public Nullable<System.DateTime> data_realizacji_zamówienia { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual ICollection<Zamówienia_produkty> Zamówienia_produkty { get; set; }
    }
}
